extends RefCounted
## Idioma do menu: português, inglês, espanhol ou chinês (parcial, fallback inglês).
## Usa o TranslationServer do Godot
## com as frases em português como chave, então Label, Button e OptionButton se
## traduzem sozinhos; textos compostos passam por tr(). Só o menu muda de idioma —
## ao entrar no vale o locale volta ao português e o jogo segue como está.
## Dados usam *_en / *_es; chinês aceita *_zh e usa *_en onde faltar.

const ARQUIVO := "user://preferencias_visuais.cfg"
const LOCALES := ["pt_BR", "en", "es", "zh_CN"]
const ROTULOS := ["Português", "English", "Español", "中文"]
## Sufixo dos campos traduzidos nos JSON, por índice de idioma.
const SUFIXOS := ["", "_en", "_es", "_zh"]

const EN := {
	# Início
	"Um vale cheio de histórias.": "A valley full of stories.",
	"JOGAR": "PLAY",
	"EXPLORAR": "EXPLORE",
	"Vagas": "Save slots",
	"Três partidas, cada uma inteira. Escolha onde jogar.": "Three games, each one whole. Choose where to play.",
	"VAGA %d · %s · DIA %d": "SLOT %d · %s · DAY %d",
	"VAGA %d · VAZIA · COMEÇAR AQUI": "SLOT %d · EMPTY · START HERE",
	"RECOMEÇAR A VAGA %d": "START SLOT %d OVER",
	"APAGA A PARTIDA DE %s · CLIQUE DE NOVO": "ERASES %s'S GAME · CLICK AGAIN",
	"MAPA": "MAP",
	"AJUSTAR": "SETTINGS",
	"SOBRE": "ABOUT",
	"SAIR": "QUIT",
	"VOLTAR": "BACK",
	"CANCELAR": "CANCEL",
	"FECHAR": "CLOSE",
	"Ver o histórico": "View changelog",
	"Home": "Home",
	"Desativar": "Mute",
	"Ativar": "Unmute",
	"Silenciar": "Mute",
	"Voltar ao padrão (%s)": "Back to default (%s)",
	"mudo": "muted",
	"Restaurar estes": "Reset these",
	"Restaurar todos": "Reset all",
	"Sons do vale voltam ao padrão.": "Valley sounds go back to default.",
	"Música, narração, falas, efeitos e ambiente voltam ao padrão.": "Music, narration, voices, effects and ambience go back to default.",
	"Todos os volumes, das duas abas, voltam ao padrão.": "Every volume, in both tabs, goes back to default.",
	"Pausar": "Pause",
	"Retomar": "Resume",
	# Sair
	"Sair do jogo?": "Quit the game?",
	"Deseja encerrar Myths’ Valley?": "Do you want to close Myths’ Valley?",
	# Mapa
	"Mapa do Vale": "Valley Map",
	"Pontos de interesse": "Points of interest",
	"1 unidade = %s m": "1 unit = %s m",
	"N ↑ · roda: zoom · arrastar: mover": "N ↑ · wheel: zoom · drag: pan",
	"Voltar ao menu": "Back to menu",
	"Fechar": "Close",
	"Mapa": "Map",
	"Menu inicial": "Main menu",
	"Mostrar informações": "Show info",
	"Ocultar informações": "Hide info",
	"Tela cheia (F11)": "Fullscreen (F11)",
	"Modo janela (F11)": "Windowed (F11)",
	"Centralizar em %s": "Center on %s",
	"Rio": "River",
	"Pedras": "Rocks",
	"Pier": "Pier",
	"Cemitério": "Cemetery",
	"Ponte": "Bridge",
	"Mirante": "Lookout",
	"Igreja": "Church",
	"Bar": "Bar",
	"Praça": "Square",
	"Restaurante": "Restaurant",
	"Fazenda": "Farm",
	"Mata": "Woods",
	"Casa da estrada": "Roadside house",
	# Histórico
	"Histórico": "Changelog",
	"O que mudou no vale a cada versão.": "What changed in the valley with each version.",
	"Idioma, tempo, sons e aparência do vale.": "Language, time, sounds and look of the valley.",
	"Quem faz o vale e de onde ele vem.": "Who makes the valley and where it comes from.",
	"Como funciona este ajuste.": "How this setting works.",
	"Página anterior": "Previous page",
	"Próxima página": "Next page",
	# Ajustes
	"Ajustes": "Settings",
	"Geral": "General",
	"Sons do vale": "Valley sounds",
	"Cenário e tempo": "Scenery and time",
	"Menu": "Menu",
	"Jogo": "Game",
	"Vale": "Valley",
	"Idioma": "Language",
	"Volume": "Volume",
	"Música": "Music",
	"Narração": "Narration",
	"Falas dos personagens": "Character voices",
	"Efeitos e passos": "Effects and footsteps",
	"Ambiente": "Ambience",
	"Cenário do menu": "Menu background",
	"Fonte do menu": "Menu font",
	"Padrão": "Default",
	"Parado": "Still",
	"Sobrevoo": "Flyover",
	"Trilha do menu": "Menu music",
	"Introdução": "Introduction",
	"Menu I": "Menu I",
	"Menu II": "Menu II",
	"Recôncavo": "Recôncavo",
	"Som dos botões": "Button sounds",
	"Original": "Original",
	"Madeira": "Wood",
	"Aves": "Birds",
	"Mar": "Sea",
	"Riacho": "Stream",
	"Fogueira": "Campfire",
	"Insetos e grilos": "Insects and crickets",
	"Paisagem sonora do menu": "Menu soundscape",
	"Silêncio": "Silence",
	"Mar e aves": "Sea and birds",
	"Cenário": "Scenery",
	"Estilo visual": "Visual style",
	"Nomes dos personagens": "Character names",
	# Cursor do mouse (04/10).
	"Interface": "Interface",
	"Cursor do mouse": "Mouse cursor",
	"Clássico": "Classic",
	"Ouro polido": "Polished gold",
	"Azulejo": "Tile",
	"Talha com punho": "Carved with cuff",
	"Pergaminho": "Parchment",
	"Luz do lampião": "Lantern light",
	# Maré, minimapa, atalhos, personagens e sons (28/09).
	"Os ajustes valem na próxima vez que o vale for montado (JOGAR).": "Changes apply the next time the valley is built (PLAY).",
	"GRAVAR NO PROJETO": "SAVE TO PROJECT",
	"GRAVADO: %d moradores, %d peças": "SAVED: %d villagers, %d pieces",
	"FECHAR EDIÇÃO": "CLOSE EDITING",
	"EDITAR": "EDIT",
	"Nome": "Name",
	"Altura (m)": "Height (m)",
	"Volume da voz (dB)": "Voice volume (dB)",
	"Postos (lugar e deslocamento em unidades)": "Posts (place and offset in units)",
	"Fala %d (balão)": "Line %d (balloon)",
	"Altura (u)": "Height (u)",
	"Largura (u)": "Width (u)",
	"Afundar (u)": "Sink (u)",
	"Tronco (raio, u)": "Trunk (radius, u)",
	"Restaurar o padrão": "Restore default",
	"HOME · voltar ao menu": "HOME · back to the menu",
	"Maré": "Tide",
	"Sem maré": "No tide",
	"Ciclo do lugar": "Local cycle",
	"Ciclo lento": "Slow cycle",
	"Rápida (ver acontecer)": "Fast (watch it happen)",
	"Um tubarão! Por pouco…": "A shark! That was close…",
	"Ler / interagir": "Read / interact",
	"Observar": "Inspect",
	"Avançar a hora": "Skip time forward",
	"Reiniciar": "Reset",
	"Alternar a câmera": "Toggle the camera",
	"Atalhos": "Shortcuts",
	"Minimapa": "Minimap",
	"%s: ler / interagir  ·  %s: observar": "%s: read / interact  ·  %s: inspect",
	"Tab ou %s: alterna a câmera  ·  Esc: trava": "Tab or %s: toggles the camera  ·  Esc: locks",
	"Rodinha: zoom  ·  %s: avança a hora": "Wheel: zoom  ·  %s: skips time",
	"%s: reinicia  ·  %s: mapa · minimapa em AJUSTAR": "%s: reset  ·  %s: map · minimap in ADJUST",
	"Câmera travada · %s ou Tab destrava": "Camera locked · %s or Tab unlocks",
	"Câmera livre · %s ou Esc trava": "Camera free · %s or Esc locks",
	"Não foi possível salvar os atalhos de teclado.": "Could not save the keyboard shortcuts.",
	"Não foi possível salvar a preferência do minimapa.": "Could not save the minimap preference.",
	"PERSONAGENS": "CHARACTERS",
	"Personagens": "Characters",
	"Moradores e peças do vale, com falas e medidas.": "The valley's people and pieces, with voices and measures.",
	"MORADORES": "VILLAGERS",
	"ASSETS": "ASSETS",
	"Filtrar por nome…": "Filter by name…",
	"Viajante (você)": "Traveler (you)",
	"É você: o recém-chegado da capital.": "It's you: the newcomer from the capital.",
	"Sem posto fixo: acompanha o viajante pelo vale.": "No fixed post: he follows the traveler around the valley.",
	"voz %s": "voice %s",
	"Ouvir a fala": "Play the line",
	"Áudio ainda não gravado": "Audio not recorded yet",
	"Nada com esse nome por aqui.": "Nothing by that name here.",
	"altura %s u": "height %s u",
	"largura %s u": "width %s u",
	"tronco %s": "trunk %s",
	"caixa": "box",
	"girar": "rotated",
	"afundar %s": "sunk %s",
	"piso %s": "deck %s",
	"manhã": "morning",
	"tarde": "afternoon",
	"entardecer": "dusk",
	"noite": "night",
	"madrugada": "small hours",
	"Árvores": "Trees",
	"Construções": "Buildings",
	"Casas": "Houses",
	"Adereços": "Props",
	"Itens": "Items",
	"Passos na água": "Steps in the water",
	"Novos": "New",
	"Ouvir": "Listen",
	"Assentando as pedras": "Setting the stones",
	# Etapas da montagem do vale (tela de carregamento).
	"Enchendo a baía": "Filling the bay",
	"Moldando o terreno": "Shaping the land",
	"Estendendo a praia e os rios": "Laying out the beach and rivers",
	"Abrindo as ruas": "Opening the streets",
	"Plantando a mata": "Planting the forest",
	"Medindo os lotes": "Measuring the plots",
	"Erguendo as casas": "Raising the houses",
	"Cercando o roçado": "Fencing the field",
	"Plantando as árvores da vila": "Planting the village trees",
	"Erguendo a capela, a venda e o píer": "Raising the chapel, the shop and the pier",
	"Espalhando os objetos": "Scattering the objects",
	"Fundeando as canoas": "Anchoring the canoes",
	"Acendendo os lampiões": "Lighting the lamps",
	"Pronto": "Ready",
	"Trocando o estilo do vale…": "Changing the valley style…",
	"Mostrar": "Show",
	"Ocultar": "Hide",
	"Tripo (modelos gerados)": "Tripo (generated models)",
	"Procedural (por código)": "Procedural (code-built)",
	"Tempo": "Time",
	"Passagem do tempo": "Time speed",
	"Parada": "Stopped",
	"Lenta": "Slow",
	"Normal": "Normal",
	"Rápida": "Fast",
	"Hora inicial": "Starting time",
	"Pausar o relógio no jogo": "Pause the clock in game",
	"Permitido": "Allowed",
	"Bloqueado": "Locked",
	"Teclas de movimento": "Movement keys",
	"Setas": "Arrows",
	"WASD e setas": "WASD and arrows",
	"Madrugada (4h30)": "Before dawn (4:30)",
	"Manhã (7h)": "Morning (7:00)",
	"Meio-dia": "Noon",
	"Tarde (15h)": "Afternoon (15:00)",
	"Entardecer (17h30)": "Dusk (17:30)",
	"Noite (20h30)": "Night (20:30)",
	# Conhecer
	"Por trás do vale": "Behind the valley",
	"Colaboradores": "Contributors",
	"O vale nasceu do encontro entre paisagens, memórias e histórias brasileiras. Entre casas, caminhos e mata, cada lugar convida a uma descoberta.": "The valley was born where Brazilian landscapes, memories and stories meet. Among houses, paths and woods, every place invites a discovery.",
	"Música, narração e efeitos acompanham a travessia e dão voz aos lugares e personagens. Esta é uma primeira visita a esse mundo. Obrigado por caminhar conosco enquanto a jornada cresce.": "Music, narration and sound effects follow the crossing and give voice to places and characters. This is a first visit to this world. Thank you for walking with us while the journey grows.",
	"Myths’ Valley é uma criação da equipe da Alpha Centauri, um spin-off do projeto Batalha de Mitos. Você pode saber mais acessando:": "Myths’ Valley is created by the Alpha Centauri team, a spin-off of the Batalha de Mitos project. You can learn more at:",
	# Travessia
	"A partida": "The departure",
	"A travessia": "The crossing",
	"A chegada": "The arrival",
	"CONTINUAR": "CONTINUE",
	"PULAR": "SKIP",
	"Carregando o vale…": "Loading the valley…",
	"Do almanaque": "From the almanac",
	"Dizem no vale": "Valley lore",
	"O mar do vale segue a carta náutica 1108 da Marinha, com a água da preamar de sizígia.": "The valley's sea follows the Brazilian Navy's nautical chart 1108, with the water at spring high tide.",
	"Toda a costa da baía é franjada de coqueiro, inclinado para o mar como quem procura a água.": "The whole shore of the bay is fringed with coconut palms, leaning toward the sea as if looking for the water.",
	"Em 1887 a piaçava sai da Bahia em fardos para o mundo: vira vassoura, corda de navio e cobertura de rancho.": "In 1887 piassava fiber leaves Bahia in bales for the world: it becomes brooms, ship's rope and thatch for huts.",
	"Onde o rio encontra a baía, quem manda é o mangue-vermelho, de pé na lama salgada.": "Where the river meets the bay, the red mangrove rules, standing in the salty mud.",
	"O dendezeiro veio da costa da África; do dendê sai o azeite do acarajé, do vatapá e da moqueca.": "The oil palm came from the coast of Africa; its dendê gives the oil for acarajé, vatapá and moqueca.",
	"Em 1887 já é raro achar um pau-brasil de pé na mata.": "By 1887 a standing brazilwood tree is already a rare sight in the forest.",
	"O jenipapo verde tinge a pele de azul-escuro por dias; maduro, vira o licor das festas de São João.": "Unripe genipap stains the skin dark blue for days; ripe, it becomes the liqueur of the São João festivals.",
	"Disse também, sem tirar a mão do leme, que ali a gente aprende a não andar na mata depois que escurece.": "He also said, without taking his hand off the tiller, that there you learn not to walk in the woods after dark.",
	"Minha avó diz que o que troca com a gente à noite, cobra de dia. — Pedro": "My grandmother says that whatever trades with you at night collects by day. — Pedro",
	"Para o povo de santo, a gameleira é morada de Iroko, e não se corta. Os mais velhos passam longe dela à noite.": "For the Candomblé faithful, the gameleira fig is Iroko's home and is never cut. The elders keep away from it at night.",
	"Maré cheia, ninguém anda no mangue.": "At high tide, nobody walks in the mangrove.",
	"Ninguém dorme debaixo de jaqueira carregada.": "Nobody sleeps under a jackfruit tree heavy with fruit.",
	# A atualização pelo site (abertura, embaixo da versão).
	"Nova versão: Build %d · Atualizar": "New version: Build %d · Update",
	"Nova versão: Build %d · Baixar no site": "New version: Build %d · Download from the site",
	"Baixando a Build %d… %d%%": "Downloading Build %d… %d%%",
	"Conferindo o arquivo…": "Checking the file…",
	"Instalando a Build %d…": "Installing Build %d…",
	"Build %d instalada · Reiniciar o jogo": "Build %d installed · Restart the game",
	"A atualização falhou · Tentar de novo": "The update failed · Try again",
}

const ES := {
	"Um vale cheio de histórias.": "Un valle lleno de historias.",
	"JOGAR": "JUGAR",
	"EXPLORAR": "EXPLORAR",
	"Vagas": "Ranuras",
	"Três partidas, cada uma inteira. Escolha onde jogar.": "Tres partidas, cada una entera. Elige dónde jugar.",
	"VAGA %d · %s · DIA %d": "RANURA %d · %s · DÍA %d",
	"VAGA %d · VAZIA · COMEÇAR AQUI": "RANURA %d · VACÍA · EMPEZAR AQUÍ",
	"RECOMEÇAR A VAGA %d": "EMPEZAR DE NUEVO LA RANURA %d",
	"APAGA A PARTIDA DE %s · CLIQUE DE NOVO": "BORRA LA PARTIDA DE %s · HAZ CLIC OTRA VEZ",
	"MAPA": "MAPA",
	"AJUSTAR": "AJUSTES",
	"SOBRE": "ACERCA DE",
	"SAIR": "SALIR",
	"VOLTAR": "VOLVER",
	"CANCELAR": "CANCELAR",
	"FECHAR": "CERRAR",
	"Ver o histórico": "Ver el historial",
	"Home": "Inicio",
	"Desativar": "Silenciar",
	"Ativar": "Activar",
	"Silenciar": "Silenciar",
	"Voltar ao padrão (%s)": "Volver al predeterminado (%s)",
	"mudo": "silenciado",
	"Restaurar estes": "Restaurar estos",
	"Restaurar todos": "Restaurar todos",
	"Sons do vale voltam ao padrão.": "Los sonidos del valle vuelven al predeterminado.",
	"Música, narração, falas, efeitos e ambiente voltam ao padrão.": "Música, narración, voces, efectos y ambiente vuelven al predeterminado.",
	"Todos os volumes, das duas abas, voltam ao padrão.": "Todos los volúmenes, de las dos pestañas, vuelven al predeterminado.",
	"Pausar": "Pausar",
	"Retomar": "Reanudar",
	"Sair do jogo?": "¿Salir del juego?",
	"Deseja encerrar Myths’ Valley?": "¿Quieres cerrar Myths’ Valley?",
	"Mapa do Vale": "Mapa del Valle",
	"Pontos de interesse": "Puntos de interés",
	"1 unidade = %s m": "1 unidad = %s m",
	"N ↑ · roda: zoom · arrastar: mover": "N ↑ · rueda: zoom · arrastrar: mover",
	"Voltar ao menu": "Volver al menú",
	"Fechar": "Cerrar",
	"Mapa": "Mapa",
	"Menu inicial": "Menú principal",
	"Mostrar informações": "Mostrar información",
	"Ocultar informações": "Ocultar información",
	"Tela cheia (F11)": "Pantalla completa (F11)",
	"Modo janela (F11)": "Modo ventana (F11)",
	"Centralizar em %s": "Centrar en %s",
	"Rio": "Río",
	"Pedras": "Rocas",
	"Pier": "Muelle",
	"Cemitério": "Cementerio",
	"Ponte": "Puente",
	"Mirante": "Mirador",
	"Igreja": "Iglesia",
	"Bar": "Bar",
	"Praça": "Plaza",
	"Restaurante": "Restaurante",
	"Fazenda": "Hacienda",
	"Mata": "Bosque",
	"Casa da estrada": "Casa del camino",
	"Histórico": "Historial",
	"O que mudou no vale a cada versão.": "Lo que cambió en el valle en cada versión.",
	"Idioma, tempo, sons e aparência do vale.": "Idioma, tiempo, sonidos y aspecto del valle.",
	"Quem faz o vale e de onde ele vem.": "Quién hace el valle y de dónde viene.",
	"Como funciona este ajuste.": "Cómo funciona este ajuste.",
	"Página anterior": "Página anterior",
	"Próxima página": "Página siguiente",
	"Ajustes": "Ajustes",
	"Geral": "General",
	"Sons do vale": "Sonidos del valle",
	"Cenário e tempo": "Escenario y tiempo",
	"Menu": "Menú",
	"Jogo": "Juego",
	"Vale": "Valle",
	"Idioma": "Idioma",
	"Volume": "Volumen",
	"Música": "Música",
	"Narração": "Narración",
	"Falas dos personagens": "Voces de los personajes",
	"Efeitos e passos": "Efectos y pasos",
	"Ambiente": "Ambiente",
	"Cenário do menu": "Fondo del menú",
	"Fonte do menu": "Fuente del menú",
	"Padrão": "Predeterminada",
	"Parado": "Fijo",
	"Sobrevoo": "Sobrevuelo",
	"Trilha do menu": "Música del menú",
	"Introdução": "Introducción",
	"Menu I": "Menú I",
	"Menu II": "Menú II",
	"Recôncavo": "Recôncavo",
	"Som dos botões": "Sonido de los botones",
	"Original": "Original",
	"Madeira": "Madera",
	"Aves": "Aves",
	"Mar": "Mar",
	"Riacho": "Arroyo",
	"Fogueira": "Hoguera",
	"Insetos e grilos": "Insectos y grillos",
	"Paisagem sonora do menu": "Paisaje sonoro del menú",
	"Silêncio": "Silencio",
	"Mar e aves": "Mar y aves",
	"Cenário": "Escenario",
	"Estilo visual": "Estilo visual",
	"Nomes dos personagens": "Nombres de los personajes",
	# Cursor do mouse (04/10).
	"Interface": "Interfaz",
	"Cursor do mouse": "Cursor del ratón",
	"Clássico": "Clásico",
	"Ouro polido": "Oro pulido",
	"Azulejo": "Azulejo",
	"Talha com punho": "Talla con puño",
	"Pergaminho": "Pergamino",
	"Luz do lampião": "Luz del farol",
	# Marea, minimapa, atajos, personajes y sonidos (28/09).
	"Os ajustes valem na próxima vez que o vale for montado (JOGAR).": "Los ajustes valen la próxima vez que se monte el valle (JUGAR).",
	"GRAVAR NO PROJETO": "GUARDAR EN EL PROYECTO",
	"GRAVADO: %d moradores, %d peças": "GUARDADO: %d vecinos, %d piezas",
	"FECHAR EDIÇÃO": "CERRAR EDICIÓN",
	"EDITAR": "EDITAR",
	"Nome": "Nombre",
	"Altura (m)": "Altura (m)",
	"Volume da voz (dB)": "Volumen de la voz (dB)",
	"Postos (lugar e deslocamento em unidades)": "Puestos (lugar y desplazamiento en unidades)",
	"Fala %d (balão)": "Frase %d (globo)",
	"Altura (u)": "Altura (u)",
	"Largura (u)": "Ancho (u)",
	"Afundar (u)": "Hundir (u)",
	"Tronco (raio, u)": "Tronco (radio, u)",
	"Restaurar o padrão": "Restaurar lo predeterminado",
	"HOME · voltar ao menu": "HOME · volver al menú",
	"Maré": "Marea",
	"Sem maré": "Sin marea",
	"Ciclo do lugar": "Ciclo del lugar",
	"Ciclo lento": "Ciclo lento",
	"Rápida (ver acontecer)": "Rápida (verla pasar)",
	"Um tubarão! Por pouco…": "¡Un tiburón! Por poco…",
	"Ler / interagir": "Leer / interactuar",
	"Observar": "Observar",
	"Avançar a hora": "Avanzar la hora",
	"Reiniciar": "Reiniciar",
	"Alternar a câmera": "Alternar la cámara",
	"Atalhos": "Atajos",
	"Minimapa": "Minimapa",
	"%s: ler / interagir  ·  %s: observar": "%s: leer / interactuar  ·  %s: observar",
	"Tab ou %s: alterna a câmera  ·  Esc: trava": "Tab o %s: alterna la cámara  ·  Esc: fija",
	"Rodinha: zoom  ·  %s: avança a hora": "Rueda: zoom  ·  %s: avanza la hora",
	"%s: reinicia  ·  %s: mapa · minimapa em AJUSTAR": "%s: reinicia  ·  %s: mapa · minimapa en AJUSTAR",
	"Câmera travada · %s ou Tab destrava": "Cámara fija · %s o Tab la suelta",
	"Câmera livre · %s ou Esc trava": "Cámara libre · %s o Esc la fija",
	"Não foi possível salvar os atalhos de teclado.": "No se pudieron guardar los atajos de teclado.",
	"Não foi possível salvar a preferência do minimapa.": "No se pudo guardar la preferencia del minimapa.",
	"PERSONAGENS": "PERSONAJES",
	"Personagens": "Personajes",
	"Moradores e peças do vale, com falas e medidas.": "Los habitantes y las piezas del valle, con voces y medidas.",
	"MORADORES": "VECINOS",
	"ASSETS": "RECURSOS",
	"Filtrar por nome…": "Filtrar por nombre…",
	"Viajante (você)": "Viajero (tú)",
	"É você: o recém-chegado da capital.": "Eres tú: el recién llegado de la capital.",
	"Sem posto fixo: acompanha o viajante pelo vale.": "Sin puesto fijo: acompaña al viajero por el valle.",
	"voz %s": "voz %s",
	"Ouvir a fala": "Escuchar la frase",
	"Áudio ainda não gravado": "Audio aún no grabado",
	"Nada com esse nome por aqui.": "Nada con ese nombre por aquí.",
	"altura %s u": "altura %s u",
	"largura %s u": "ancho %s u",
	"tronco %s": "tronco %s",
	"caixa": "caja",
	"girar": "girado",
	"afundar %s": "hundido %s",
	"piso %s": "piso %s",
	"manhã": "mañana",
	"tarde": "tarde",
	"entardecer": "atardecer",
	"noite": "noche",
	"madrugada": "madrugada",
	"Árvores": "Árboles",
	"Construções": "Construcciones",
	"Casas": "Casas",
	"Adereços": "Objetos",
	"Itens": "Ítems",
	"Passos na água": "Pasos en el agua",
	"Novos": "Nuevos",
	"Ouvir": "Escuchar",
	"Assentando as pedras": "Asentando las piedras",
	# Etapas da montagem del valle (pantalla de carga).
	"Enchendo a baía": "Llenando la bahía",
	"Moldando o terreno": "Modelando el terreno",
	"Estendendo a praia e os rios": "Extendiendo la playa y los ríos",
	"Abrindo as ruas": "Abriendo las calles",
	"Plantando a mata": "Plantando el bosque",
	"Medindo os lotes": "Midiendo los lotes",
	"Erguendo as casas": "Levantando las casas",
	"Cercando o roçado": "Cercando el sembrado",
	"Plantando as árvores da vila": "Plantando los árboles del pueblo",
	"Erguendo a capela, a venda e o píer": "Levantando la capilla, la tienda y el muelle",
	"Espalhando os objetos": "Esparciendo los objetos",
	"Fundeando as canoas": "Fondeando las canoas",
	"Acendendo os lampiões": "Encendiendo los faroles",
	"Pronto": "Listo",
	"Trocando o estilo do vale…": "Cambiando el estilo del valle…",
	"Mostrar": "Mostrar",
	"Ocultar": "Ocultar",
	"Tripo (modelos gerados)": "Tripo (modelos generados)",
	"Procedural (por código)": "Procedural (por código)",
	"Tempo": "Tiempo",
	"Passagem do tempo": "Paso del tiempo",
	"Parada": "Detenido",
	"Lenta": "Lento",
	"Normal": "Normal",
	"Rápida": "Rápido",
	"Hora inicial": "Hora inicial",
	"Pausar o relógio no jogo": "Pausar el reloj en el juego",
	"Permitido": "Permitido",
	"Bloqueado": "Bloqueado",
	"Teclas de movimento": "Teclas de movimiento",
	"Setas": "Flechas",
	"WASD e setas": "WASD y flechas",
	"Madrugada (4h30)": "Madrugada (4:30)",
	"Manhã (7h)": "Mañana (7:00)",
	"Meio-dia": "Mediodía",
	"Tarde (15h)": "Tarde (15:00)",
	"Entardecer (17h30)": "Atardecer (17:30)",
	"Noite (20h30)": "Noche (20:30)",
	"Por trás do vale": "Detrás del valle",
	"Colaboradores": "Colaboradores",
	"O vale nasceu do encontro entre paisagens, memórias e histórias brasileiras. Entre casas, caminhos e mata, cada lugar convida a uma descoberta.": "El valle nació del encuentro entre paisajes, memorias e historias brasileñas. Entre casas, caminos y bosque, cada lugar invita a un descubrimiento.",
	"Música, narração e efeitos acompanham a travessia e dão voz aos lugares e personagens. Esta é uma primeira visita a esse mundo. Obrigado por caminhar conosco enquanto a jornada cresce.": "La música, la narración y los efectos acompañan la travesía y dan voz a los lugares y personajes. Esta es una primera visita a este mundo. Gracias por caminar con nosotros mientras el viaje crece.",
	"Myths’ Valley é uma criação da equipe da Alpha Centauri, um spin-off do projeto Batalha de Mitos. Você pode saber mais acessando:": "Myths’ Valley es una creación del equipo de Alpha Centauri, un spin-off del proyecto Batalha de Mitos. Puedes saber más en:",
	"A partida": "La partida",
	"A travessia": "La travesía",
	"A chegada": "La llegada",
	"CONTINUAR": "CONTINUAR",
	"PULAR": "SALTAR",
	"Carregando o vale…": "Cargando el valle…",
	"Do almanaque": "Del almanaque",
	"Dizem no vale": "Dicen en el valle",
	"O mar do vale segue a carta náutica 1108 da Marinha, com a água da preamar de sizígia.": "El mar del valle sigue la carta náutica 1108 de la Marina de Brasil, con el agua de la pleamar de sicigias.",
	"Toda a costa da baía é franjada de coqueiro, inclinado para o mar como quem procura a água.": "Toda la costa de la bahía está bordeada de cocoteros, inclinados hacia el mar como quien busca el agua.",
	"Em 1887 a piaçava sai da Bahia em fardos para o mundo: vira vassoura, corda de navio e cobertura de rancho.": "En 1887 la piasava sale de Bahía en fardos hacia el mundo: se vuelve escoba, cabo de barco y techo de rancho.",
	"Onde o rio encontra a baía, quem manda é o mangue-vermelho, de pé na lama salgada.": "Donde el río se encuentra con la bahía, manda el mangle rojo, de pie en el lodo salado.",
	"O dendezeiro veio da costa da África; do dendê sai o azeite do acarajé, do vatapá e da moqueca.": "La palma aceitera vino de la costa de África; del dendê sale el aceite del acarajé, el vatapá y la moqueca.",
	"Em 1887 já é raro achar um pau-brasil de pé na mata.": "En 1887 ya es raro encontrar un palo brasil en pie en el bosque.",
	"O jenipapo verde tinge a pele de azul-escuro por dias; maduro, vira o licor das festas de São João.": "El jenipapo verde tiñe la piel de azul oscuro por días; maduro, se vuelve el licor de las fiestas de San Juan.",
	"Disse também, sem tirar a mão do leme, que ali a gente aprende a não andar na mata depois que escurece.": "Dijo también, sin soltar el timón, que allí uno aprende a no andar por el bosque después de que oscurece.",
	"Minha avó diz que o que troca com a gente à noite, cobra de dia. — Pedro": "Mi abuela dice que lo que negocia con uno de noche, cobra de día. — Pedro",
	"Para o povo de santo, a gameleira é morada de Iroko, e não se corta. Os mais velhos passam longe dela à noite.": "Para el pueblo de santo, la gameleira es morada de Iroko, y no se corta. Los mayores pasan lejos de ella de noche.",
	"Maré cheia, ninguém anda no mangue.": "Con marea alta, nadie anda por el manglar.",
	"Ninguém dorme debaixo de jaqueira carregada.": "Nadie duerme debajo de una jaquera cargada.",
	# A atualização pelo site (abertura, embaixo da versão).
	"Nova versão: Build %d · Atualizar": "Nueva versión: Build %d · Actualizar",
	"Nova versão: Build %d · Baixar no site": "Nueva versión: Build %d · Descargar del sitio",
	"Baixando a Build %d… %d%%": "Descargando la Build %d… %d%%",
	"Conferindo o arquivo…": "Verificando el archivo…",
	"Instalando a Build %d…": "Instalando la Build %d…",
	"Build %d instalada · Reiniciar o jogo": "Build %d instalada · Reiniciar el juego",
	"A atualização falhou · Tentar de novo": "La actualización falló · Intentar de nuevo",
}

## Uma tradução fica registrada só enquanto o menu está no idioma dela: registrada,
## o Godot a usaria como fallback (locale padrão "en") também em português.
static var _traducao: Translation


static func indice() -> int:
	return indice_preferido(OS.get_locale_language())


## A escolha salva vence; sem ela, o sistema apenas sugere o idioma.
static func indice_preferido(lingua_sistema: String) -> int:
	var preferencias := ConfigFile.new()
	if preferencias.load(ARQUIVO) == OK and preferencias.has_section_key("menu", "idioma"):
		return clampi(int(preferencias.get_value("menu", "idioma")), 0, LOCALES.size() - 1)
	return indice_do_sistema(lingua_sistema)


static func indice_do_sistema(lingua: String) -> int:
	var codigo := lingua.to_lower().replace("-", "_").get_slice("_", 0)
	return {"pt": 0, "en": 1, "es": 2, "zh": 3}.get(codigo, 1)


static func ingles() -> bool:
	return indice() in [1, 3]


static func sufixo() -> String:
	return SUFIXOS[indice()]


static func definir(novo: int) -> void:
	var preferencias := ConfigFile.new()
	preferencias.load(ARQUIVO)
	preferencias.set_value("menu", "idioma", clampi(novo, 0, LOCALES.size() - 1))
	if preferencias.save(ARQUIVO) != OK:
		push_warning("Não foi possível salvar o idioma do menu.")
	aplicar_menu()


## Liga o idioma escolhido enquanto o menu está aberto.
static func aplicar_menu() -> void:
	restaurar_jogo()
	var atual := indice()
	if atual == 0:
		return
	# Chinês ainda em preparação: fallback inglês explícito na tela inicial.
	var frases: Dictionary = (EN if atual in [1, 3] else ES).duplicate()
	if atual == 3:
		var dados: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/selecao_idioma.json"))
		for chave: String in dados.get("menu_zh", {}):
			frases[chave] = dados["menu_zh"][chave]
	_traducao = Translation.new()
	_traducao.locale = LOCALES[atual]
	for chave: String in frases:
		_traducao.add_message(chave, frases[chave])
	TranslationServer.add_translation(_traducao)
	TranslationServer.set_locale(LOCALES[atual])


## O jogo ainda não tem tradução: ao sair do menu, tudo volta ao português.
static func restaurar_jogo() -> void:
	if _traducao != null and TranslationServer.has_translation(_traducao):
		TranslationServer.remove_translation(_traducao)
	_traducao = null
	TranslationServer.set_locale(LOCALES[0])


## Campo no idioma do menu: *_en / *_es / *_zh, com fallback inglês para chinês.
static func campo(dados: Dictionary, chave: String, padrao: Variant = "") -> Variant:
	return campo_no_idioma(dados, chave, indice(), padrao)


## Prévia de texto sem alterar o locale nem a preferência salva.
static func campo_no_idioma(dados: Dictionary, chave: String, atual: int, padrao: Variant = "") -> Variant:
	atual = clampi(atual, 0, LOCALES.size() - 1)
	var traduzida: String = chave + SUFIXOS[atual]
	if traduzida != chave and dados.has(traduzida):
		return dados[traduzida]
	if atual == 3 and dados.has(chave + "_en"):
		return dados[chave + "_en"]
	return dados.get(chave, padrao)
