extends RefCounted
## Idioma do menu: português, inglês, espanhol ou chinês (parcial, fallback inglês).
## Usa o TranslationServer do Godot
## com as frases em português como chave, então Label, Button e OptionButton se
## traduzem sozinhos; textos compostos passam por tr(). Só o menu muda de idioma —
## ao entrar no vale o locale volta ao português e o jogo segue como está.
## Dados usam *_en / *_es; chinês aceita *_zh e usa *_en onde faltar.

const ARQUIVO := "user://preferencias_visuais.cfg"
const LOCALES := ["pt_BR", "en", "es", "zh_CN"]
const ROTULOS := ["Português", "English", "Español", "中文"]
## Sufixo dos campos traduzidos nos JSON, por índice de idioma.
const SUFIXOS := ["", "_en", "_es", "_zh"]

const EN := {
	# Início
	"Um vale cheio de histórias.": "A valley full of stories.",
	"JOGAR": "PLAY",
	"EXPLORAR": "EXPLORE",
	"Vagas": "Save slots",
	"Três partidas, cada uma inteira. Escolha onde jogar.": "Three games, each one whole. Choose where to play.",
	"VAGA %d · DIA %d": "SLOT %d · DAY %d",
	"VAGA %d · VAZIA": "SLOT %d · EMPTY",
	"COMEÇAR AQUI": "START HERE",
	"Editar o nome da vaga": "Edit the slot name",
	"Apagar a partida": "Delete the game",
	"Pontos de restauração": "Restore points",
	"APAGAR A PARTIDA DE %s?": "DELETE %s'S GAME?",
	"CLIQUE NA LIXEIRA DE NOVO": "CLICK THE BIN AGAIN",
	"Nome da vaga": "Slot name",
	"Vaga %d · %s · dia %d": "Slot %d · %s · day %d",
	"Vaga %d · vazia": "Slot %d · empty",
	"O jogo guarda um ponto por dia de jogo — os sete mais novos — e um antes de apagar ou de restaurar a partida. Restaurar volta a vaga para o ponto escolhido, e o que ela tinha fica guardado como ponto também.": "The game keeps one point per in-game day — the seven newest — and one before deleting or restoring the game. Restoring takes the slot back to the chosen point, and what it had is kept as a point too.",
	"COMEÇO DO DIA": "START OF THE DAY",
	"ANTES DE APAGAR": "BEFORE DELETING",
	"ANTES DE RESTAURAR": "BEFORE RESTORING",
	"DIA %d · %s · %s": "DAY %d · %s · %s",
	"RESTAURAR O DIA %d · CLIQUE DE NOVO": "RESTORE DAY %d · CLICK AGAIN",
	"MAPA": "MAP",
	"AJUSTAR": "SETTINGS",
	"SOBRE": "ABOUT",
	"SAIR": "QUIT",
	"VOLTAR": "BACK",
	"CANCELAR": "CANCEL",
	"FECHAR": "CLOSE",
	"Ver o histórico": "View changelog",
	"Home": "Home",
	"Desativar": "Mute",
	"Ativar": "Unmute",
	"Silenciar": "Mute",
	"Voltar ao padrão (%s)": "Back to default (%s)",
	"mudo": "muted",
	"Restaurar estes": "Reset these",
	"Restaurar todos": "Reset all",
	"Sons do vale voltam ao padrão.": "Valley sounds go back to default.",
	"Música, narração, falas, efeitos e ambiente voltam ao padrão.": "Music, narration, voices, effects and ambience go back to default.",
	"Todos os volumes, das duas abas, voltam ao padrão.": "Every volume, in both tabs, goes back to default.",
	"Pausar": "Pause",
	"Retomar": "Resume",
	# Sair
	"Sair do jogo?": "Quit the game?",
	"Deseja encerrar Myths’ Valley?": "Do you want to close Myths’ Valley?",
	# Mapa
	"Mapa do Vale": "Valley Map",
	"Pontos de interesse": "Points of interest",
	"1 unidade = %s m": "1 unit = %s m",
	"N ↑ · roda: zoom · arrastar: mover": "N ↑ · wheel: zoom · drag: pan",
	"Voltar ao menu": "Back to menu",
	"Fechar": "Close",
	"Mapa": "Map",
	"Menu inicial": "Main menu",
	"Mostrar informações": "Show info",
	"Ocultar informações": "Hide info",
	"Tela cheia (F11)": "Fullscreen (F11)",
	"Modo janela (F11)": "Windowed (F11)",
	"Centralizar em %s": "Center on %s",
	"Rio": "River",
	"Pedras": "Rocks",
	"Pier": "Pier",
	"Cemitério": "Cemetery",
	"Ponte": "Bridge",
	"Mirante": "Lookout",
	"Igreja": "Church",
	"Bar": "Bar",
	"Praça": "Square",
	"Restaurante": "Restaurant",
	"Fazenda": "Farm",
	"Mata": "Woods",
	"Casa da estrada": "Roadside house",
	# Histórico
	"Histórico": "Changelog",
	"O que mudou no vale a cada versão.": "What changed in the valley with each version.",
	"Idioma, tempo, sons e aparência do vale.": "Language, time, sounds and look of the valley.",
	"Quem faz o vale e de onde ele vem.": "Who makes the valley and where it comes from.",
	"Como funciona este ajuste.": "How this setting works.",
	"Página anterior": "Previous page",
	"Próxima página": "Next page",
	# Ajustes
	"Ajustes": "Settings",
	"Geral": "General",
	"Sons do vale": "Valley sounds",
	"Cenário e tempo": "Scenery and time",
	"Menu": "Menu",
	"Jogo": "Game",
	"Vale": "Valley",
	"Idioma": "Language",
	"Volume": "Volume",
	"Música": "Music",
	"Narração": "Narration",
	"Falas dos personagens": "Character voices",
	"Efeitos e passos": "Effects and footsteps",
	"Ambiente": "Ambience",
	"Cenário do menu": "Menu background",
	"Fonte do menu": "Menu font",
	"Padrão": "Default",
	"Parado": "Still",
	"Sobrevoo": "Flyover",
	"Trilha do menu": "Menu music",
	"Introdução": "Introduction",
	"Menu I": "Menu I",
	"Menu II": "Menu II",
	"Recôncavo": "Recôncavo",
	"Som dos botões": "Button sounds",
	"Original": "Original",
	"Madeira": "Wood",
	"Aves": "Birds",
	"Mar": "Sea",
	"Riacho": "Stream",
	"Fogueira": "Campfire",
	"Insetos e grilos": "Insects and crickets",
	"Paisagem sonora do menu": "Menu soundscape",
	"Silêncio": "Silence",
	"Mar e aves": "Sea and birds",
	"Cenário": "Scenery",
	"Estilo visual": "Visual style",
	"Nomes dos personagens": "Character names",
	# Cursor do mouse (04/10).
	"Interface": "Interface",
	"Cursor do mouse": "Mouse cursor",
	"Clássico": "Classic",
	"Ouro polido": "Polished gold",
	"Azulejo": "Tile",
	"Talha com punho": "Carved with cuff",
	"Pergaminho": "Parchment",
	"Luz do lampião": "Lantern light",
	"Tamanho do texto": "Text size",
	"Tamanho do HUD": "HUD size",
	"Pequeno": "Small",
	"Médio": "Medium",
	"Grande": "Large",
	"Muito grande": "Extra large",
	# Maré, minimapa, atalhos, personagens e sons (28/09).
	"Os ajustes valem na próxima vez que o vale for montado (JOGAR).": "Changes apply the next time the valley is built (PLAY).",
	"GRAVAR NO PROJETO": "SAVE TO PROJECT",
	"GRAVADO: %d moradores, %d peças": "SAVED: %d villagers, %d pieces",
	"FECHAR EDIÇÃO": "CLOSE EDITING",
	"EDITAR": "EDIT",
	"Nome": "Name",
	"Altura (m)": "Height (m)",
	"Volume da voz (dB)": "Voice volume (dB)",
	"Postos (lugar e deslocamento em unidades)": "Posts (place and offset in units)",
	"Fala %d (balão)": "Line %d (balloon)",
	"Altura (u)": "Height (u)",
	"Largura (u)": "Width (u)",
	"Afundar (u)": "Sink (u)",
	"Tronco (raio, u)": "Trunk (radius, u)",
	"Restaurar o padrão": "Restore default",
	"Gravar no projeto. Os ajustes valem na próxima montagem do vale.": "Save to the project. Changes apply the next time the valley is built.",
	"Gravado: %d moradores, %d peças": "Saved: %d villagers, %d pieces",
	"Editar": "Edit",
	"Fechar a edição": "Close editing",
	"Sair sem gravar?": "Leave without saving?",
	"Há ajustes que ainda não foram gravados no projeto.": "Some changes have not been saved to the project yet.",
	"Sem gravar, eles ficam só nesta máquina.": "Without saving, they stay only on this computer.",
	"GRAVAR E SAIR": "SAVE AND LEAVE",
	"SAIR SEM GRAVAR": "LEAVE WITHOUT SAVING",
	"Anterior": "Previous",
	"MODELOS": "MODELS",
	"Modelos": "Models",
	"Altura": "Height",
	"Voz": "Voice",
	"Nota": "Note",
	"Arquivo": "File",
	"Medida": "Size",
	"Tronco": "Trunk",
	"Afundar": "Sink",
	"Piso": "Floor",
	"Marcações": "Flags",
	"Arrastar: girar · roda: zoom · botão direito: mover · duplo clique: centralizar": "Drag: rotate · wheel: zoom · right button: move · double click: center",
	"Parar a fala": "Stop the line",
	"Arraste para girar": "Drag to rotate",
	"Próximo": "Next",
	"HOME · voltar ao menu": "HOME · back to the menu",
	"Maré": "Tide",
	"Sem maré": "No tide",
	"Ciclo do lugar": "Local cycle",
	"Ciclo lento": "Slow cycle",
	"Rápida (ver acontecer)": "Fast (watch it happen)",
	"Um tubarão! Por pouco…": "A shark! That was close…",
	"Ler / interagir": "Read / interact",
	"Observar": "Inspect",
	"Avançar a hora": "Skip time forward",
	"Reiniciar": "Reset",
	"Alternar a câmera": "Toggle the camera",
	"Atalhos": "Shortcuts",
	"Minimapa": "Minimap",
	"%s: ler / interagir  ·  %s: observar": "%s: read / interact  ·  %s: inspect",
	"Tab ou %s: alterna a câmera  ·  Esc: trava": "Tab or %s: toggles the camera  ·  Esc: locks",
	"Rodinha: zoom  ·  %s: avança a hora": "Wheel: zoom  ·  %s: skips time",
	"%s: reinicia  ·  %s: mapa · minimapa em AJUSTAR": "%s: reset  ·  %s: map · minimap in ADJUST",
	"Câmera travada · %s ou Tab destrava": "Camera locked · %s or Tab unlocks",
	"Câmera livre · %s ou Esc trava": "Camera free · %s or Esc locks",
	"Não foi possível salvar os atalhos de teclado.": "Could not save the keyboard shortcuts.",
	"Não foi possível salvar a preferência do minimapa.": "Could not save the minimap preference.",
	"PERSONAGENS": "CHARACTERS",
	"Personagens": "Characters",
	"Moradores e peças do vale, com falas e medidas.": "The valley's people and pieces, with voices and measures.",
	"MORADORES": "VILLAGERS",
	"ASSETS": "ASSETS",
	"Filtrar por nome…": "Filter by name…",
	"Viajante (você)": "Traveler (you)",
	"É você: o recém-chegado da capital.": "It's you: the newcomer from the capital.",
	"Sem posto fixo: acompanha o viajante pelo vale.": "No fixed post: he follows the traveler around the valley.",
	"voz %s": "voice %s",
	"Ouvir a fala": "Play the line",
	"Áudio ainda não gravado": "Audio not recorded yet",
	"Nada com esse nome por aqui.": "Nothing by that name here.",
	"altura %s u": "height %s u",
	"largura %s u": "width %s u",
	"tronco %s": "trunk %s",
	"caixa": "box",
	"girar": "rotated",
	"afundar %s": "sunk %s",
	"piso %s": "deck %s",
	"manhã": "morning",
	"tarde": "afternoon",
	"entardecer": "dusk",
	"noite": "night",
	"madrugada": "small hours",
	"Árvores": "Trees",
	"Construções": "Buildings",
	"Casas": "Houses",
	"Adereços": "Props",
	"Itens": "Items",
	"Passos na água": "Steps in the water",
	"Novos": "New",
	"Ouvir": "Listen",
	"Assentando as pedras": "Setting the stones",
	# Etapas da montagem do vale (tela de carregamento).
	"Enchendo a baía": "Filling the bay",
	"Moldando o terreno": "Shaping the land",
	"Estendendo a praia e os rios": "Laying out the beach and rivers",
	"Abrindo as ruas": "Opening the streets",
	"Plantando a mata": "Planting the forest",
	"Medindo os lotes": "Measuring the plots",
	"Erguendo as casas": "Raising the houses",
	"Cercando o roçado": "Fencing the field",
	"Plantando as árvores da vila": "Planting the village trees",
	"Erguendo a capela, a venda e o píer": "Raising the chapel, the shop and the pier",
	"Espalhando os objetos": "Scattering the objects",
	"Fundeando as canoas": "Anchoring the canoes",
	"Acendendo os lampiões": "Lighting the lamps",
	"Pronto": "Ready",
	"Trocando o estilo do vale…": "Changing the valley style…",
	"Mostrar": "Show",
	"Ocultar": "Hide",
	"Tripo (modelos gerados)": "Tripo (generated models)",
	"Procedural (por código)": "Procedural (code-built)",
	"Tempo": "Time",
	"Passagem do tempo": "Time speed",
	"Parada": "Stopped",
	"Lenta": "Slow",
	"Normal": "Normal",
	"Rápida": "Fast",
	"Hora inicial": "Starting time",
	"Teclas de movimento": "Movement keys",
	"Setas": "Arrows",
	"WASD e setas": "WASD and arrows",
	"Madrugada (4h30)": "Before dawn (4:30)",
	"Manhã (7h)": "Morning (7:00)",
	"Meio-dia": "Noon",
	"Tarde (15h)": "Afternoon (15:00)",
	"Entardecer (17h30)": "Dusk (17:30)",
	"Noite (20h30)": "Night (20:30)",
	# Conhecer
	"Por trás do vale": "Behind the valley",
	"Colaboradores": "Contributors",
	"O vale nasceu do encontro entre paisagens, memórias e histórias brasileiras. Entre casas, caminhos e mata, cada lugar convida a uma descoberta.": "The valley was born where Brazilian landscapes, memories and stories meet. Among houses, paths and woods, every place invites a discovery.",
	"Música, narração e efeitos acompanham a travessia e dão voz aos lugares e personagens. Esta é uma primeira visita a esse mundo. Obrigado por caminhar conosco enquanto a jornada cresce.": "Music, narration and sound effects follow the crossing and give voice to places and characters. This is a first visit to this world. Thank you for walking with us while the journey grows.",
	"Myths’ Valley é uma criação da equipe da Alpha Centauri, um spin-off do projeto Batalha de Mitos. Você pode saber mais acessando:": "Myths’ Valley is created by the Alpha Centauri team, a spin-off of the Batalha de Mitos project. You can learn more at:",
	# Travessia
	"A partida": "The departure",
	"A travessia": "The crossing",
	"A chegada": "The arrival",
	"CONTINUAR": "CONTINUE",
	"PULAR": "SKIP",
	"Carregando o vale…": "Loading the valley…",
	"Do almanaque": "From the almanac",
	"Dizem no vale": "Valley lore",
	"O mar do vale segue a carta náutica 1108 da Marinha, com a água da preamar de sizígia.": "The valley's sea follows the Brazilian Navy's nautical chart 1108, with the water at spring high tide.",
	"Toda a costa da baía é franjada de coqueiro, inclinado para o mar como quem procura a água.": "The whole shore of the bay is fringed with coconut palms, leaning toward the sea as if looking for the water.",
	"Em 1887 a piaçava sai da Bahia em fardos para o mundo: vira vassoura, corda de navio e cobertura de rancho.": "In 1887 piassava fiber leaves Bahia in bales for the world: it becomes brooms, ship's rope and thatch for huts.",
	"Onde o rio encontra a baía, quem manda é o mangue-vermelho, de pé na lama salgada.": "Where the river meets the bay, the red mangrove rules, standing in the salty mud.",
	"O dendezeiro veio da costa da África; do dendê sai o azeite do acarajé, do vatapá e da moqueca.": "The oil palm came from the coast of Africa; its dendê gives the oil for acarajé, vatapá and moqueca.",
	"Em 1887 já é raro achar um pau-brasil de pé na mata.": "By 1887 a standing brazilwood tree is already a rare sight in the forest.",
	"O jenipapo verde tinge a pele de azul-escuro por dias; maduro, vira o licor das festas de São João.": "Unripe genipap stains the skin dark blue for days; ripe, it becomes the liqueur of the São João festivals.",
	"Disse também, sem tirar a mão do leme, que ali a gente aprende a não andar na mata depois que escurece.": "He also said, without taking his hand off the tiller, that there you learn not to walk in the woods after dark.",
	"Minha avó diz que o que troca com a gente à noite, cobra de dia. — Pedro": "My grandmother says that whatever trades with you at night collects by day. — Pedro",
	"Para o povo de santo, a gameleira é morada de Iroko, e não se corta. Os mais velhos passam longe dela à noite.": "For the Candomblé faithful, the gameleira fig is Iroko's home and is never cut. The elders keep away from it at night.",
	"Maré cheia, ninguém anda no mangue.": "At high tide, nobody walks in the mangrove.",
	"Ninguém dorme debaixo de jaqueira carregada.": "Nobody sleeps under a jackfruit tree heavy with fruit.",
	# Menu do Esc: o relógio e a tela de controles
	"Relógio: %s": "Clock: %s",
	"Recebido de %s: %s": "Received from %s: %s",
	"%d réis": "%d réis",
	"Faça a obra: %s": "Build: %s",
	"Entrar: %s": "Enter: %s",
	"Sair": "Leave",
	"Nova missão: %s  ·  [%s] para acompanhar": "New quest: %s  ·  [%s] to track",
	"Junte %s": "Gather %s",
	"Corte %s": "Cut %s",
	"Leve %s a %s": "Take %s to %s",
	"Fale com %s": "Talk to %s",
	"Concluído: missões com %s": "Done: tasks with %s",
	"Parar o relógio?": "Stop the clock?",
	"Com o relógio parado, esta partida perde as conquistas daqui para frente — mesmo que você volte a ligá-lo depois.": "With the clock stopped, this game loses achievements from now on — even if you start it again later.",
	"DEIXAR CORRER": "KEEP RUNNING",
	"PARAR O RELÓGIO": "STOP THE CLOCK",
	"Ponha na mão: %s.": "Put it in hand: %s.",
	# O alvo duro: o aço que falta na mão e o talento que falta na teia (Recursos3D._o_que_impede).
	"Pede %s e o talento %s.": "Needs %s and the talent %s.",
	"pede %s e o talento %s": "needs %s and the talent %s",
	"Pede %s.": "Needs %s.",
	"pede %s": "needs %s",
	"Pede o talento %s.": "Needs the talent %s.",
	"pede o talento %s": "needs the talent %s",
	"ponha na mão: %s": "put it in hand: %s",
	"selecione %s (%s)": "select %s (%s)",
	"Relógio: %s · sem conquistas": "Clock: %s · no achievements",
	"Relógio: %s · pausa bloqueada": "Clock: %s · pause locked",
	"Pausar o relógio está bloqueado em AJUSTAR → Geral.": "Pausing the clock is locked in SETTINGS → General.",
	"A mudança fica no registro do relógio, no save.": "The change is kept in the clock log, in the save.",
	"Adiantar o relógio?": "Move the clock forward?",
	"Pular uma hora tira as conquistas desta partida daqui para frente.": "Skipping an hour turns off achievements for this game from now on.",
	"DEIXAR COMO ESTÁ": "LEAVE IT",
	"ADIANTAR UMA HORA": "SKIP ONE HOUR",
	"O tempo está em \"Parada\" no AJUSTAR: esta partida não conta conquistas.": "Time is set to \"Stopped\" in SETTINGS: this game earns no achievements.",
	"Pausar o relógio no jogo": "Pause the clock in game",
	"Permitido": "Allowed",
	"Bloqueado": "Locked",
	"Rezar": "Pray",
	"Oferendar": "Make an offering",
	"Olhar": "Look",
	# A casa herdada (#50): a tecla da cama e do baú, e o nome lá dentro.
	"Dormir": "Sleep",
	"Baú": "Chest",
	# O E nos moradores (tecla_dos_moradores.gd) e a tela da missão cumprida
	# (conquista_da_missao.gd).
	"Falar": "Talk",
	"Entregar": "Hand over",
	"Missão concluída": "Quest complete",
	# O E na bancada da oficina e na fogueira (tecla_das_bancadas.gd).
	"Oficina": "Workshop",
	"Canteiro": "Site table",
	"Cozinhar": "Cook",
	"Obras": "Works",
	"Sua casa": "Your house",
	"Casa do Pedro": "Pedro's house",
	"Casa da Dona Zefa": "Dona Zefa's house",
	# O folheto de cordel: a assinatura, o preço e as teclas do pé do papel.
	"por %s": "by %s",
	"%d réis na feira": "%d réis at the fair",
	"[%s] guardar  ·  [%s] coleção": "[%s] keep  ·  [%s] collection",
	"Fé  ›  nenhuma ainda": "Faith  ›  none yet",
	"Fé %s  ›  %s        nível %d  ·  %d/%d de experiência  ·  %s": "%s faith  ›  %s        level %d  ·  %d/%d experience  ·  %s",
	"↑↓ ou W/S: andar    ·    ←→ ou A/D: trocar de raiz    ·    E ou Enter: destravar    ·    Tab: %s    ·    %s ou Esc: fechar": "↑↓ or W/S: move    ·    ←→ or A/D: change root    ·    E or Enter: unlock    ·    Tab: %s    ·    %s or Esc: close",
	"a teia da fé": "the web of faith",
	"a teia de ofício": "the web of crafts",
	"Regras da fé": "Rules of faith",
	"Você ainda não é de fé nenhuma. No arraial há três, e cada uma se escolhe com os pés: no marco dela.": "You do not follow any faith yet. The village has three, and each one is chosen on foot: at its own landmark.",
	"Uma fé por vez. A que você deixar congela inteira, e trocar de novo não apaga nada.": "One faith at a time. The one you leave freezes whole, and switching again erases nothing.",
	"Você é %s: nível %d, %d ponto(s) para gastar.": "You follow %s: level %d, %d point(s) to spend.",
	"%s está congelada no nível %d, com %d ponto(s) e %d de acumulado. Voltar a ela devolve a teia como ficou.": "%s is frozen at level %d, with %d point(s) and %d gathered. Going back to it returns the web as it was.",
	"Cada marco da sua fé dá graça uma vez a cada %d dia(s): fôlego, experiência de fé e uma bênção que dura %d dia(s).": "Each landmark of your faith gives grace once every %d day(s): stamina, faith experience and a blessing that lasts %d day(s).",
	"dá graça hoje": "gives grace today",
	"a graça volta no %s": "grace returns on %s",
	"Bênção de agora: %s, por mais %d dia(s).": "Current blessing: %s, for %d more day(s).",
	"Nenhuma bênção agora.": "No blessing right now.",
	"A festa da sua fé: %s. Nesse dia o marco dá graça mesmo fora do prazo, e quem é da fé se junta lá à tarde.": "The feast of your faith: %s. On that day the landmark gives grace even out of turn, and the faithful gather there in the afternoon.",
	"Trocar de fé não apaga nada: a teia de agora congela inteira e para de valer. Levar o acumulado junto custa caro: de cada cem pontos, chegam quinze.": "Switching faith erases nothing: the current web freezes whole and stops counting. Bringing what you gathered costs dearly: of every hundred points, fifteen arrive.",
	"Cruzeiro": "Wayside cross",
	"Igreja do Bom Jesus": "Bom Jesus church",
	"Capela velha": "Old chapel",
	"Terreiro": "Terreiro",
	"Gameleira": "Gameleira",
	"à mão": "by hand",
	"andando": "running",
	"parado": "stopped",
	"Controles": "Controls",
	"Teclas fixas": "Fixed keys",
	"Restaurar padrão": "Restore defaults",
	"Voltar": "Back",
	"Aperte uma letra…": "Press a letter…",
	"Andar": "Walk",
	"Correr": "Run",
	"Pular": "Jump",
	"Espaço": "Space",
	"Item na mão": "Item in hand",
	"1 a 0 · rodinha": "1 to 0 · mouse wheel",
	"Gestos": "Gestures",
	"Aproximar e afastar": "Zoom in and out",
	"Ctrl + rodinha · + e −": "Ctrl + wheel · + and −",
	"Andar até o ponto": "Walk to a point",
	"Botão direito (duplo: correr)": "Right click (double: run)",
	"Aperte a letra nova    ·    Esc: desistir": "Press the new letter    ·    Esc: cancel",
	"↑↓ ou W/S: andar    ·    E ou Enter: trocar a tecla    ·    Esc: voltar ao menu": "↑↓ or W/S: move    ·    E or Enter: change key    ·    Esc: back to menu",
	"Só letras de A a Z. Escolha outra, ou Esc para desistir.": "Letters A to Z only. Pick another, or Esc to cancel.",
	"W, A, S e D andam e navegam as telas. Escolha outra letra.": "W, A, S and D walk and navigate screens. Pick another letter.",
	"%s agora na %s. %s passou para a %s.": "%s is now on %s. %s moved to %s.",
	"%s agora na %s.": "%s is now on %s.",
	"As teclas voltaram ao padrão.": "Keys are back to default.",
	# A ferramenta que a missão entrega fica na barra (CadeiaDeMissoes._por_na_barra).
	"Recebido: %s. Aperte %s para usar.": "Received: %s. Press %s to use it.",
	"Recebido: %s, na mochila. Arraste para a barra de mão (%s abre a mochila).": "Received: %s, in the backpack. Drag it to the hand bar (%s opens the backpack).",
	# O aviso de quem ficou para trás na condução (prototype_hud.set_aviso_de_espera).
	"%s está esperando você: volte para perto para seguir.": "%s is waiting for you: head back to keep going.",
	# A atualização pelo site (abertura, embaixo da versão).
	"Nova versão: Build %d · Atualizar": "New version: Build %d · Update",
	"Nova versão: Build %d · Baixar no site": "New version: Build %d · Download from the site",
	"Baixando a Build %d… %d%%": "Downloading Build %d… %d%%",
	"Conferindo o arquivo…": "Checking the file…",
	"Instalando a Build %d…": "Installing Build %d…",
	"Build %d instalada · Reiniciar o jogo": "Build %d installed · Restart the game",
	"A atualização falhou · Tentar de novo": "The update failed · Try again",
	"Edição Tripothon · atualização desativada": "Tripothon Edition · updates turned off",
}

const ES := {
	"Um vale cheio de histórias.": "Un valle lleno de historias.",
	"JOGAR": "JUGAR",
	"EXPLORAR": "EXPLORAR",
	"Vagas": "Ranuras",
	"Três partidas, cada uma inteira. Escolha onde jogar.": "Tres partidas, cada una entera. Elige dónde jugar.",
	"VAGA %d · DIA %d": "RANURA %d · DÍA %d",
	"VAGA %d · VAZIA": "RANURA %d · VACÍA",
	"COMEÇAR AQUI": "EMPEZAR AQUÍ",
	"Editar o nome da vaga": "Editar el nombre de la ranura",
	"Apagar a partida": "Borrar la partida",
	"Pontos de restauração": "Puntos de restauración",
	"APAGAR A PARTIDA DE %s?": "¿BORRAR LA PARTIDA DE %s?",
	"CLIQUE NA LIXEIRA DE NOVO": "HAZ CLIC EN LA PAPELERA DE NUEVO",
	"Nome da vaga": "Nombre de la ranura",
	"Vaga %d · %s · dia %d": "Ranura %d · %s · día %d",
	"Vaga %d · vazia": "Ranura %d · vacía",
	"O jogo guarda um ponto por dia de jogo — os sete mais novos — e um antes de apagar ou de restaurar a partida. Restaurar volta a vaga para o ponto escolhido, e o que ela tinha fica guardado como ponto também.": "El juego guarda un punto por día de juego — los siete más nuevos — y uno antes de borrar o restaurar la partida. Restaurar devuelve la ranura al punto elegido, y lo que tenía queda guardado como punto también.",
	"COMEÇO DO DIA": "INICIO DEL DÍA",
	"ANTES DE APAGAR": "ANTES DE BORRAR",
	"ANTES DE RESTAURAR": "ANTES DE RESTAURAR",
	"DIA %d · %s · %s": "DÍA %d · %s · %s",
	"RESTAURAR O DIA %d · CLIQUE DE NOVO": "RESTAURAR EL DÍA %d · HAZ CLIC DE NUEVO",
	"MAPA": "MAPA",
	"AJUSTAR": "AJUSTES",
	"SOBRE": "ACERCA DE",
	"SAIR": "SALIR",
	"VOLTAR": "VOLVER",
	"CANCELAR": "CANCELAR",
	"FECHAR": "CERRAR",
	"Ver o histórico": "Ver el historial",
	"Home": "Inicio",
	"Desativar": "Silenciar",
	"Ativar": "Activar",
	"Silenciar": "Silenciar",
	"Voltar ao padrão (%s)": "Volver al predeterminado (%s)",
	"mudo": "silenciado",
	"Restaurar estes": "Restaurar estos",
	"Restaurar todos": "Restaurar todos",
	"Sons do vale voltam ao padrão.": "Los sonidos del valle vuelven al predeterminado.",
	"Música, narração, falas, efeitos e ambiente voltam ao padrão.": "Música, narración, voces, efectos y ambiente vuelven al predeterminado.",
	"Todos os volumes, das duas abas, voltam ao padrão.": "Todos los volúmenes, de las dos pestañas, vuelven al predeterminado.",
	"Pausar": "Pausar",
	"Retomar": "Reanudar",
	"Sair do jogo?": "¿Salir del juego?",
	"Deseja encerrar Myths’ Valley?": "¿Quieres cerrar Myths’ Valley?",
	"Mapa do Vale": "Mapa del Valle",
	"Pontos de interesse": "Puntos de interés",
	"1 unidade = %s m": "1 unidad = %s m",
	"N ↑ · roda: zoom · arrastar: mover": "N ↑ · rueda: zoom · arrastrar: mover",
	"Voltar ao menu": "Volver al menú",
	"Fechar": "Cerrar",
	"Mapa": "Mapa",
	"Menu inicial": "Menú principal",
	"Mostrar informações": "Mostrar información",
	"Ocultar informações": "Ocultar información",
	"Tela cheia (F11)": "Pantalla completa (F11)",
	"Modo janela (F11)": "Modo ventana (F11)",
	"Centralizar em %s": "Centrar en %s",
	"Rio": "Río",
	"Pedras": "Rocas",
	"Pier": "Muelle",
	"Cemitério": "Cementerio",
	"Ponte": "Puente",
	"Mirante": "Mirador",
	"Igreja": "Iglesia",
	"Bar": "Bar",
	"Praça": "Plaza",
	"Restaurante": "Restaurante",
	"Fazenda": "Hacienda",
	"Mata": "Bosque",
	"Casa da estrada": "Casa del camino",
	"Histórico": "Historial",
	"O que mudou no vale a cada versão.": "Lo que cambió en el valle en cada versión.",
	"Idioma, tempo, sons e aparência do vale.": "Idioma, tiempo, sonidos y aspecto del valle.",
	"Quem faz o vale e de onde ele vem.": "Quién hace el valle y de dónde viene.",
	"Como funciona este ajuste.": "Cómo funciona este ajuste.",
	"Página anterior": "Página anterior",
	"Próxima página": "Página siguiente",
	"Ajustes": "Ajustes",
	"Geral": "General",
	"Sons do vale": "Sonidos del valle",
	"Cenário e tempo": "Escenario y tiempo",
	"Menu": "Menú",
	"Jogo": "Juego",
	"Vale": "Valle",
	"Idioma": "Idioma",
	"Volume": "Volumen",
	"Música": "Música",
	"Narração": "Narración",
	"Falas dos personagens": "Voces de los personajes",
	"Efeitos e passos": "Efectos y pasos",
	"Ambiente": "Ambiente",
	"Cenário do menu": "Fondo del menú",
	"Fonte do menu": "Fuente del menú",
	"Padrão": "Predeterminada",
	"Parado": "Fijo",
	"Sobrevoo": "Sobrevuelo",
	"Trilha do menu": "Música del menú",
	"Introdução": "Introducción",
	"Menu I": "Menú I",
	"Menu II": "Menú II",
	"Recôncavo": "Recôncavo",
	"Som dos botões": "Sonido de los botones",
	"Original": "Original",
	"Madeira": "Madera",
	"Aves": "Aves",
	"Mar": "Mar",
	"Riacho": "Arroyo",
	"Fogueira": "Hoguera",
	"Insetos e grilos": "Insectos y grillos",
	"Paisagem sonora do menu": "Paisaje sonoro del menú",
	"Silêncio": "Silencio",
	"Mar e aves": "Mar y aves",
	"Cenário": "Escenario",
	"Estilo visual": "Estilo visual",
	"Nomes dos personagens": "Nombres de los personajes",
	# Cursor do mouse (04/10).
	"Interface": "Interfaz",
	"Cursor do mouse": "Cursor del ratón",
	"Clássico": "Clásico",
	"Ouro polido": "Oro pulido",
	"Azulejo": "Azulejo",
	"Talha com punho": "Talla con puño",
	"Pergaminho": "Pergamino",
	"Luz do lampião": "Luz del farol",
	"Tamanho do texto": "Tamaño del texto",
	"Tamanho do HUD": "Tamaño del HUD",
	"Pequeno": "Pequeño",
	"Médio": "Mediano",
	"Grande": "Grande",
	"Muito grande": "Muy grande",
	# Marea, minimapa, atajos, personajes y sonidos (28/09).
	"Os ajustes valem na próxima vez que o vale for montado (JOGAR).": "Los ajustes valen la próxima vez que se monte el valle (JUGAR).",
	"GRAVAR NO PROJETO": "GUARDAR EN EL PROYECTO",
	"GRAVADO: %d moradores, %d peças": "GUARDADO: %d vecinos, %d piezas",
	"FECHAR EDIÇÃO": "CERRAR EDICIÓN",
	"EDITAR": "EDITAR",
	"Nome": "Nombre",
	"Altura (m)": "Altura (m)",
	"Volume da voz (dB)": "Volumen de la voz (dB)",
	"Postos (lugar e deslocamento em unidades)": "Puestos (lugar y desplazamiento en unidades)",
	"Fala %d (balão)": "Frase %d (globo)",
	"Altura (u)": "Altura (u)",
	"Largura (u)": "Ancho (u)",
	"Afundar (u)": "Hundir (u)",
	"Tronco (raio, u)": "Tronco (radio, u)",
	"Restaurar o padrão": "Restaurar lo predeterminado",
	"Gravar no projeto. Os ajustes valem na próxima montagem do vale.": "Guardar en el proyecto. Los ajustes valen en el próximo montaje del valle.",
	"Gravado: %d moradores, %d peças": "Guardado: %d vecinos, %d piezas",
	"Editar": "Editar",
	"Fechar a edição": "Cerrar la edición",
	"Sair sem gravar?": "¿Salir sin guardar?",
	"Há ajustes que ainda não foram gravados no projeto.": "Hay ajustes que aún no se guardaron en el proyecto.",
	"Sem gravar, eles ficam só nesta máquina.": "Sin guardar, se quedan solo en este equipo.",
	"GRAVAR E SAIR": "GUARDAR Y SALIR",
	"SAIR SEM GRAVAR": "SALIR SIN GUARDAR",
	"Anterior": "Anterior",
	"MODELOS": "MODELOS",
	"Modelos": "Modelos",
	"Altura": "Altura",
	"Voz": "Voz",
	"Nota": "Nota",
	"Arquivo": "Archivo",
	"Medida": "Medida",
	"Tronco": "Tronco",
	"Afundar": "Hundir",
	"Piso": "Piso",
	"Marcações": "Marcas",
	"Arrastar: girar · roda: zoom · botão direito: mover · duplo clique: centralizar": "Arrastrar: girar · rueda: zoom · botón derecho: mover · doble clic: centrar",
	"Parar a fala": "Detener la frase",
	"Arraste para girar": "Arrastra para girar",
	"Próximo": "Siguiente",
	"HOME · voltar ao menu": "HOME · volver al menú",
	"Maré": "Marea",
	"Sem maré": "Sin marea",
	"Ciclo do lugar": "Ciclo del lugar",
	"Ciclo lento": "Ciclo lento",
	"Rápida (ver acontecer)": "Rápida (verla pasar)",
	"Um tubarão! Por pouco…": "¡Un tiburón! Por poco…",
	"Ler / interagir": "Leer / interactuar",
	"Observar": "Observar",
	"Avançar a hora": "Avanzar la hora",
	"Reiniciar": "Reiniciar",
	"Alternar a câmera": "Alternar la cámara",
	"Atalhos": "Atajos",
	"Minimapa": "Minimapa",
	"%s: ler / interagir  ·  %s: observar": "%s: leer / interactuar  ·  %s: observar",
	"Tab ou %s: alterna a câmera  ·  Esc: trava": "Tab o %s: alterna la cámara  ·  Esc: fija",
	"Rodinha: zoom  ·  %s: avança a hora": "Rueda: zoom  ·  %s: avanza la hora",
	"%s: reinicia  ·  %s: mapa · minimapa em AJUSTAR": "%s: reinicia  ·  %s: mapa · minimapa en AJUSTAR",
	"Câmera travada · %s ou Tab destrava": "Cámara fija · %s o Tab la suelta",
	"Câmera livre · %s ou Esc trava": "Cámara libre · %s o Esc la fija",
	"Não foi possível salvar os atalhos de teclado.": "No se pudieron guardar los atajos de teclado.",
	"Não foi possível salvar a preferência do minimapa.": "No se pudo guardar la preferencia del minimapa.",
	"PERSONAGENS": "PERSONAJES",
	"Personagens": "Personajes",
	"Moradores e peças do vale, com falas e medidas.": "Los habitantes y las piezas del valle, con voces y medidas.",
	"MORADORES": "VECINOS",
	"ASSETS": "RECURSOS",
	"Filtrar por nome…": "Filtrar por nombre…",
	"Viajante (você)": "Viajero (tú)",
	"É você: o recém-chegado da capital.": "Eres tú: el recién llegado de la capital.",
	"Sem posto fixo: acompanha o viajante pelo vale.": "Sin puesto fijo: acompaña al viajero por el valle.",
	"voz %s": "voz %s",
	"Ouvir a fala": "Escuchar la frase",
	"Áudio ainda não gravado": "Audio aún no grabado",
	"Nada com esse nome por aqui.": "Nada con ese nombre por aquí.",
	"altura %s u": "altura %s u",
	"largura %s u": "ancho %s u",
	"tronco %s": "tronco %s",
	"caixa": "caja",
	"girar": "girado",
	"afundar %s": "hundido %s",
	"piso %s": "piso %s",
	"manhã": "mañana",
	"tarde": "tarde",
	"entardecer": "atardecer",
	"noite": "noche",
	"madrugada": "madrugada",
	"Árvores": "Árboles",
	"Construções": "Construcciones",
	"Casas": "Casas",
	"Adereços": "Objetos",
	"Itens": "Ítems",
	"Passos na água": "Pasos en el agua",
	"Novos": "Nuevos",
	"Ouvir": "Escuchar",
	"Assentando as pedras": "Asentando las piedras",
	# Etapas da montagem del valle (pantalla de carga).
	"Enchendo a baía": "Llenando la bahía",
	"Moldando o terreno": "Modelando el terreno",
	"Estendendo a praia e os rios": "Extendiendo la playa y los ríos",
	"Abrindo as ruas": "Abriendo las calles",
	"Plantando a mata": "Plantando el bosque",
	"Medindo os lotes": "Midiendo los lotes",
	"Erguendo as casas": "Levantando las casas",
	"Cercando o roçado": "Cercando el sembrado",
	"Plantando as árvores da vila": "Plantando los árboles del pueblo",
	"Erguendo a capela, a venda e o píer": "Levantando la capilla, la tienda y el muelle",
	"Espalhando os objetos": "Esparciendo los objetos",
	"Fundeando as canoas": "Fondeando las canoas",
	"Acendendo os lampiões": "Encendiendo los faroles",
	"Pronto": "Listo",
	"Trocando o estilo do vale…": "Cambiando el estilo del valle…",
	"Mostrar": "Mostrar",
	"Ocultar": "Ocultar",
	"Tripo (modelos gerados)": "Tripo (modelos generados)",
	"Procedural (por código)": "Procedural (por código)",
	"Tempo": "Tiempo",
	"Passagem do tempo": "Paso del tiempo",
	"Parada": "Detenido",
	"Lenta": "Lento",
	"Normal": "Normal",
	"Rápida": "Rápido",
	"Hora inicial": "Hora inicial",
	"Teclas de movimento": "Teclas de movimiento",
	"Setas": "Flechas",
	"WASD e setas": "WASD y flechas",
	"Madrugada (4h30)": "Madrugada (4:30)",
	"Manhã (7h)": "Mañana (7:00)",
	"Meio-dia": "Mediodía",
	"Tarde (15h)": "Tarde (15:00)",
	"Entardecer (17h30)": "Atardecer (17:30)",
	"Noite (20h30)": "Noche (20:30)",
	"Por trás do vale": "Detrás del valle",
	"Colaboradores": "Colaboradores",
	"O vale nasceu do encontro entre paisagens, memórias e histórias brasileiras. Entre casas, caminhos e mata, cada lugar convida a uma descoberta.": "El valle nació del encuentro entre paisajes, memorias e historias brasileñas. Entre casas, caminos y bosque, cada lugar invita a un descubrimiento.",
	"Música, narração e efeitos acompanham a travessia e dão voz aos lugares e personagens. Esta é uma primeira visita a esse mundo. Obrigado por caminhar conosco enquanto a jornada cresce.": "La música, la narración y los efectos acompañan la travesía y dan voz a los lugares y personajes. Esta es una primera visita a este mundo. Gracias por caminar con nosotros mientras el viaje crece.",
	"Myths’ Valley é uma criação da equipe da Alpha Centauri, um spin-off do projeto Batalha de Mitos. Você pode saber mais acessando:": "Myths’ Valley es una creación del equipo de Alpha Centauri, un spin-off del proyecto Batalha de Mitos. Puedes saber más en:",
	"A partida": "La partida",
	"A travessia": "La travesía",
	"A chegada": "La llegada",
	"CONTINUAR": "CONTINUAR",
	"PULAR": "SALTAR",
	"Carregando o vale…": "Cargando el valle…",
	"Do almanaque": "Del almanaque",
	"Dizem no vale": "Dicen en el valle",
	"O mar do vale segue a carta náutica 1108 da Marinha, com a água da preamar de sizígia.": "El mar del valle sigue la carta náutica 1108 de la Marina de Brasil, con el agua de la pleamar de sicigias.",
	"Toda a costa da baía é franjada de coqueiro, inclinado para o mar como quem procura a água.": "Toda la costa de la bahía está bordeada de cocoteros, inclinados hacia el mar como quien busca el agua.",
	"Em 1887 a piaçava sai da Bahia em fardos para o mundo: vira vassoura, corda de navio e cobertura de rancho.": "En 1887 la piasava sale de Bahía en fardos hacia el mundo: se vuelve escoba, cabo de barco y techo de rancho.",
	"Onde o rio encontra a baía, quem manda é o mangue-vermelho, de pé na lama salgada.": "Donde el río se encuentra con la bahía, manda el mangle rojo, de pie en el lodo salado.",
	"O dendezeiro veio da costa da África; do dendê sai o azeite do acarajé, do vatapá e da moqueca.": "La palma aceitera vino de la costa de África; del dendê sale el aceite del acarajé, el vatapá y la moqueca.",
	"Em 1887 já é raro achar um pau-brasil de pé na mata.": "En 1887 ya es raro encontrar un palo brasil en pie en el bosque.",
	"O jenipapo verde tinge a pele de azul-escuro por dias; maduro, vira o licor das festas de São João.": "El jenipapo verde tiñe la piel de azul oscuro por días; maduro, se vuelve el licor de las fiestas de San Juan.",
	"Disse também, sem tirar a mão do leme, que ali a gente aprende a não andar na mata depois que escurece.": "Dijo también, sin soltar el timón, que allí uno aprende a no andar por el bosque después de que oscurece.",
	"Minha avó diz que o que troca com a gente à noite, cobra de dia. — Pedro": "Mi abuela dice que lo que negocia con uno de noche, cobra de día. — Pedro",
	"Para o povo de santo, a gameleira é morada de Iroko, e não se corta. Os mais velhos passam longe dela à noite.": "Para el pueblo de santo, la gameleira es morada de Iroko, y no se corta. Los mayores pasan lejos de ella de noche.",
	"Maré cheia, ninguém anda no mangue.": "Con marea alta, nadie anda por el manglar.",
	"Ninguém dorme debaixo de jaqueira carregada.": "Nadie duerme debajo de una jaquera cargada.",
	# Menu do Esc: o relógio e a tela de controles
	"Relógio: %s": "Reloj: %s",
	"Recebido de %s: %s": "Recibido de %s: %s",
	"%d réis": "%d reales",
	"Faça a obra: %s": "Haz la obra: %s",
	"Entrar: %s": "Entrar: %s",
	"Sair": "Salir",
	"Nova missão: %s  ·  [%s] para acompanhar": "Nueva misión: %s  ·  [%s] para seguirla",
	"Junte %s": "Junta %s",
	"Corte %s": "Corta %s",
	"Leve %s a %s": "Lleva %s a %s",
	"Fale com %s": "Habla con %s",
	"Concluído: missões com %s": "Hecho: tareas con %s",
	"Parar o relógio?": "¿Detener el reloj?",
	"Com o relógio parado, esta partida perde as conquistas daqui para frente — mesmo que você volte a ligá-lo depois.": "Con el reloj detenido, esta partida pierde los logros de aquí en adelante, aunque vuelvas a encenderlo después.",
	"DEIXAR CORRER": "DEJAR QUE CORRA",
	"PARAR O RELÓGIO": "DETENER EL RELOJ",
	"Ponha na mão: %s.": "Tómalo en la mano: %s.",
	"Pede %s e o talento %s.": "Pide %s y el talento %s.",
	"pede %s e o talento %s": "pide %s y el talento %s",
	"Pede %s.": "Pide %s.",
	"pede %s": "pide %s",
	"Pede o talento %s.": "Pide el talento %s.",
	"pede o talento %s": "pide el talento %s",
	"ponha na mão: %s": "tómalo en la mano: %s",
	"selecione %s (%s)": "elige %s (%s)",
	"Relógio: %s · sem conquistas": "Reloj: %s · sin logros",
	"Relógio: %s · pausa bloqueada": "Reloj: %s · pausa bloqueada",
	"Pausar o relógio está bloqueado em AJUSTAR → Geral.": "Pausar el reloj está bloqueado en AJUSTES → General.",
	"A mudança fica no registro do relógio, no save.": "El cambio queda en el registro del reloj, en la partida guardada.",
	"Adiantar o relógio?": "¿Adelantar el reloj?",
	"Pular uma hora tira as conquistas desta partida daqui para frente.": "Saltar una hora quita los logros de esta partida de aquí en adelante.",
	"DEIXAR COMO ESTÁ": "DEJARLO ASÍ",
	"ADIANTAR UMA HORA": "ADELANTAR UNA HORA",
	"O tempo está em \"Parada\" no AJUSTAR: esta partida não conta conquistas.": "El tiempo está en \"Detenido\" en AJUSTES: esta partida no cuenta logros.",
	"Pausar o relógio no jogo": "Pausar el reloj en el juego",
	"Permitido": "Permitido",
	"Bloqueado": "Bloqueado",
	"Rezar": "Rezar",
	"Oferendar": "Ofrendar",
	"Olhar": "Mirar",
	"Dormir": "Dormir",
	"Baú": "Baúl",
	# O E nos moradores (tecla_dos_moradores.gd) e a tela da missão cumprida
	# (conquista_da_missao.gd).
	"Falar": "Hablar",
	"Entregar": "Dar",
	"Missão concluída": "Misión cumplida",
	# O E na bancada da oficina e na fogueira (tecla_das_bancadas.gd).
	"Oficina": "Taller",
	"Canteiro": "Mesa de obras",
	"Cozinhar": "Cocinar",
	"Obras": "Obras",
	"Sua casa": "Tu casa",
	"Casa do Pedro": "Casa de Pedro",
	"Casa da Dona Zefa": "Casa de Doña Zefa",
	"por %s": "por %s",
	"%d réis na feira": "%d reales en la feria",
	"[%s] guardar  ·  [%s] coleção": "[%s] guardar  ·  [%s] colección",
	"Fé  ›  nenhuma ainda": "Fe  ›  ninguna todavía",
	"Fé %s  ›  %s        nível %d  ·  %d/%d de experiência  ·  %s": "Fe %s  ›  %s        nivel %d  ·  %d/%d de experiencia  ·  %s",
	"↑↓ ou W/S: andar    ·    ←→ ou A/D: trocar de raiz    ·    E ou Enter: destravar    ·    Tab: %s    ·    %s ou Esc: fechar": "↑↓ o W/S: moverse    ·    ←→ o A/D: cambiar de raíz    ·    E o Enter: desbloquear    ·    Tab: %s    ·    %s o Esc: cerrar",
	"a teia da fé": "la red de la fe",
	"a teia de ofício": "la red de oficios",
	"Regras da fé": "Reglas de la fe",
	"Você ainda não é de fé nenhuma. No arraial há três, e cada uma se escolhe com os pés: no marco dela.": "Todavía no eres de ninguna fe. En el caserío hay tres, y cada una se elige con los pies: en su hito.",
	"Uma fé por vez. A que você deixar congela inteira, e trocar de novo não apaga nada.": "Una fe a la vez. La que dejes se congela entera, y cambiar de nuevo no borra nada.",
	"Você é %s: nível %d, %d ponto(s) para gastar.": "Eres %s: nivel %d, %d punto(s) por gastar.",
	"%s está congelada no nível %d, com %d ponto(s) e %d de acumulado. Voltar a ela devolve a teia como ficou.": "%s está congelada en el nivel %d, con %d punto(s) y %d acumulado. Volver a ella devuelve la red como quedó.",
	"Cada marco da sua fé dá graça uma vez a cada %d dia(s): fôlego, experiência de fé e uma bênção que dura %d dia(s).": "Cada hito de tu fe da gracia una vez cada %d día(s): aliento, experiencia de fe y una bendición que dura %d día(s).",
	"dá graça hoje": "da gracia hoy",
	"a graça volta no %s": "la gracia vuelve el %s",
	"Bênção de agora: %s, por mais %d dia(s).": "Bendición actual: %s, por %d día(s) más.",
	"Nenhuma bênção agora.": "Ninguna bendición ahora.",
	"A festa da sua fé: %s. Nesse dia o marco dá graça mesmo fora do prazo, e quem é da fé se junta lá à tarde.": "La fiesta de tu fe: %s. Ese día el hito da gracia aunque no toque, y los de la fe se reúnen allí por la tarde.",
	"Trocar de fé não apaga nada: a teia de agora congela inteira e para de valer. Levar o acumulado junto custa caro: de cada cem pontos, chegam quinze.": "Cambiar de fe no borra nada: la red actual se congela entera y deja de valer. Llevar lo acumulado cuesta caro: de cada cien puntos, llegan quince.",
	"Cruzeiro": "Crucero",
	"Igreja do Bom Jesus": "Iglesia del Bom Jesus",
	"Capela velha": "Capilla vieja",
	"Terreiro": "Terreiro",
	"Gameleira": "Gameleira",
	"à mão": "a mano",
	"andando": "en marcha",
	"parado": "detenido",
	"Controles": "Controles",
	"Teclas fixas": "Teclas fijas",
	"Restaurar padrão": "Restaurar valores",
	"Voltar": "Volver",
	"Aperte uma letra…": "Pulsa una letra…",
	"Andar": "Caminar",
	"Correr": "Correr",
	"Pular": "Saltar",
	"Espaço": "Espacio",
	"Item na mão": "Objeto en la mano",
	"1 a 0 · rodinha": "1 a 0 · rueda del ratón",
	"Gestos": "Gestos",
	"Aproximar e afastar": "Acercar y alejar",
	"Ctrl + rodinha · + e −": "Ctrl + rueda · + y −",
	"Andar até o ponto": "Caminar hasta el punto",
	"Botão direito (duplo: correr)": "Botón derecho (doble: correr)",
	"Aperte a letra nova    ·    Esc: desistir": "Pulsa la letra nueva    ·    Esc: cancelar",
	"↑↓ ou W/S: andar    ·    E ou Enter: trocar a tecla    ·    Esc: voltar ao menu": "↑↓ o W/S: moverse    ·    E o Enter: cambiar la tecla    ·    Esc: volver al menú",
	"Só letras de A a Z. Escolha outra, ou Esc para desistir.": "Solo letras de la A a la Z. Elige otra, o Esc para cancelar.",
	"W, A, S e D andam e navegam as telas. Escolha outra letra.": "W, A, S y D caminan y navegan las pantallas. Elige otra letra.",
	"%s agora na %s. %s passou para a %s.": "%s ahora en la %s. %s pasó a la %s.",
	"%s agora na %s.": "%s ahora en la %s.",
	"As teclas voltaram ao padrão.": "Las teclas volvieron a los valores de fábrica.",
	"Recebido: %s. Aperte %s para usar.": "Recibido: %s. Pulsa %s para usar.",
	"Recebido: %s, na mochila. Arraste para a barra de mão (%s abre a mochila).": "Recibido: %s, en la mochila. Arrastra a la barra de mano (%s abre la mochila).",
	"%s está esperando você: volte para perto para seguir.": "%s te está esperando: vuelve cerca para seguir.",
	# A atualização pelo site (abertura, embaixo da versão).
	"Nova versão: Build %d · Atualizar": "Nueva versión: Build %d · Actualizar",
	"Nova versão: Build %d · Baixar no site": "Nueva versión: Build %d · Descargar del sitio",
	"Baixando a Build %d… %d%%": "Descargando la Build %d… %d%%",
	"Conferindo o arquivo…": "Verificando el archivo…",
	"Instalando a Build %d…": "Instalando la Build %d…",
	"Build %d instalada · Reiniciar o jogo": "Build %d instalada · Reiniciar el juego",
	"A atualização falhou · Tentar de novo": "La actualización falló · Intentar de nuevo",
	"Edição Tripothon · atualização desativada": "Edición Tripothon · actualización desactivada",
}

## Uma tradução fica registrada só enquanto o menu está no idioma dela: registrada,
## o Godot a usaria como fallback (locale padrão "en") também em português.
static var _traducao: Translation


static func indice() -> int:
	return indice_preferido(OS.get_locale_language())


## A escolha salva vence; sem ela, o sistema apenas sugere o idioma.
static func indice_preferido(lingua_sistema: String) -> int:
	var preferencias := ConfigFile.new()
	if preferencias.load(ARQUIVO) == OK and preferencias.has_section_key("menu", "idioma"):
		return clampi(int(preferencias.get_value("menu", "idioma")), 0, LOCALES.size() - 1)
	return indice_do_sistema(lingua_sistema)


## Índice da última escolha salva; -1 se o jogador ainda não escolheu.
static func escolha_salva() -> int:
	var preferencias := ConfigFile.new()
	if preferencias.load(ARQUIVO) == OK and preferencias.has_section_key("menu", "idioma"):
		return clampi(int(preferencias.get_value("menu", "idioma")), 0, LOCALES.size() - 1)
	return -1


## Índice do idioma do sistema quando o jogo o tem; -1 para os outros (que caem no inglês).
static func idioma_do_sistema(lingua: String) -> int:
	var codigo := lingua.to_lower().replace("-", "_").get_slice("_", 0)
	return {"pt": 0, "en": 1, "es": 2, "zh": 3}.get(codigo, -1)


static func indice_do_sistema(lingua: String) -> int:
	var codigo := lingua.to_lower().replace("-", "_").get_slice("_", 0)
	return {"pt": 0, "en": 1, "es": 2, "zh": 3}.get(codigo, 1)


static func ingles() -> bool:
	return indice() in [1, 3]


static func sufixo() -> String:
	return SUFIXOS[indice()]


static func definir(novo: int) -> void:
	var preferencias := ConfigFile.new()
	preferencias.load(ARQUIVO)
	preferencias.set_value("menu", "idioma", clampi(novo, 0, LOCALES.size() - 1))
	if preferencias.save(ARQUIVO) != OK:
		push_warning("Não foi possível salvar o idioma do menu.")
	aplicar_menu()


## Liga o idioma escolhido enquanto o menu está aberto.
static func aplicar_menu() -> void:
	restaurar_jogo()
	var atual := indice()
	if atual == 0:
		return
	# Chinês ainda em preparação: fallback inglês explícito na tela inicial.
	var frases: Dictionary = (EN if atual in [1, 3] else ES).duplicate()
	if atual == 3:
		var dados: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/selecao_idioma.json"))
		for chave: String in dados.get("menu_zh", {}):
			frases[chave] = dados["menu_zh"][chave]
	_traducao = Translation.new()
	_traducao.locale = LOCALES[atual]
	for chave: String in frases:
		_traducao.add_message(chave, frases[chave])
	TranslationServer.add_translation(_traducao)
	TranslationServer.set_locale(LOCALES[atual])


## O jogo ainda não tem tradução: ao sair do menu, tudo volta ao português.
static func restaurar_jogo() -> void:
	if _traducao != null and TranslationServer.has_translation(_traducao):
		TranslationServer.remove_translation(_traducao)
	_traducao = null
	TranslationServer.set_locale(LOCALES[0])


## Campo no idioma do menu: *_en / *_es / *_zh, com fallback inglês para chinês.
static func campo(dados: Dictionary, chave: String, padrao: Variant = "") -> Variant:
	return campo_no_idioma(dados, chave, indice(), padrao)


## Prévia de texto sem alterar o locale nem a preferência salva.
static func campo_no_idioma(dados: Dictionary, chave: String, atual: int, padrao: Variant = "") -> Variant:
	atual = clampi(atual, 0, LOCALES.size() - 1)
	var traduzida: String = chave + SUFIXOS[atual]
	if traduzida != chave and dados.has(traduzida):
		return dados[traduzida]
	if atual == 3 and dados.has(chave + "_en"):
		return dados[chave + "_en"]
	return dados.get(chave, padrao)
